### ISSUE TITLE
cmake configuration

### ISSUE THREAD

**Issue by decrispell** [VisionSystemsInc/pyvxl#16]
https://github.com/VisionSystemsInc/pyvxl/blob/2700ee6174504ae1433abe5b302f05d269033159/CMakeLists.txt#L7-L29

@andyneff Should we always perform this configuration?  It was originally added so that pyvxl could be built "standalone", but much (all?) of it has to be copy/pasted into the containing project when not building standalone.   The goal would be to have users set VXL_DIR, PYBIND11_DIR, etc and then just include the pyvxl directory.

**Comment by decrispell** [comment]
Nevermind.  I think the user would still have to add the "include_directories" commands to their CMakeLists, since the ones here wouldn't get propagated back to the parent scope.  There's got to be a better way...  @deuscovrigus  would your "interface" magic solve this?

**Comment by deuscovrigus** [comment]
I recall that you need the VXL_BINARY_DIR for cmake to parse the VXLConfig.cmake. Without it stuff doesn't work. AFAIK, the cmake interface is used to handle includes and compiler definitions

**Comment by decrispell** [comment]
I believe VXLConfig.cmake is only relevant if you're using a pre-built and installed version of vxl, which we don't usually do because we tend to also be making changes to vxl itself.
