### ISSUE TITLE
contrib needed for pyvpgl

### ISSUE THREAD

**Issue by decrispell** [VisionSystemsInc/pyvxl#51]
https://github.com/VisionSystemsInc/pyvxl/blob/63b0c1fb9d8bb4a8b43853e174d8de72891193fc/vpgl/pyvpgl.cxx#L27

Is it necessary to include a brl header here just for a simple bounding box clip?   It means the brl include libraries have to be added to the user's include path, even if they're not interested in contrib.

**Comment by decrispell** [comment]
On a related note, this whole function looks more like an actual implementation than a "wrapping" to me.   Can the function be moved to brl somewhere, and then wrapped in the appropriate pyvxl place?

https://github.com/VisionSystemsInc/pyvxl/blob/63b0c1fb9d8bb4a8b43853e174d8de72891193fc/vpgl/pyvpgl.cxx#L323-L369

**Comment by decrispell** [comment]
@NoahRJohnson @andyneff

**Comment by drewgilliam** [comment]
contrib removed from pyvpgl in PR #56, implementation code as separate issue. #57.
